hw6 is done
Ltaudato1/tinkoff_edu pull request #8
Opened 2023-11-19 01:17 UTC by Ltaudato1

2023-11-24 13:29 UTC, easylaneof requested changes

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task1/DiskMap.java
> +            for (String key : inMemoryMap.keySet()) {
тут лучше использовать `entrySet()`, чтобы не делать `get(key)` внутри цикла

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task1/DiskMap.java
> +            return;
тоже самое с исключением

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task1/DiskMap.java
> +            return;
не думаю, что это правильно скрывать от пользователя исключение, лучше пробрасывать

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task1/DiskMap.java
> +        saveToDisk();
[note] для этого задания не критично, но запись на диск при каждом put -- не очень оптимально

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test1.java
> +public class Test1 {
Тест лучше называть также, как тестируемый класс, аля
`class FooService` и `class FooServiceTest`

и класть в тот же пакет, в котором лежит класс

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task1/DiskMap.java
> +package edu.hw6.Task1;
пакеты именуют маленькими

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test1.java
> +    @DisplayName("test for correct writing")
лучше правильно называть сам тест, тогда необязательно писать `@DisplayName`

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test1.java
> +    void test() throws IOException {
в имени метода нужно описывать то, что ты тестируешь, слово `test` - ничего не означает)

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test1.java
> +            Arguments.of(Map.ofEntries(
[note] лучше используй `Map.of()`

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test1.java
> +        return Stream.of(
не очень понятно, зачем делать параметризированный тест с только одним набором аргументов

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task2.java
> +        fileName = fileName.substring(0, fileName.lastIndexOf("."));
```suggestion
String fileName = path.toString().substring(0, ...)
```

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test2/The_Real_Tinkoff_Bank_Biggest_Secret.txt
> +Категории кэшбэка выпадают на рандоме
😨

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test2/The_Real_Tinkoff_Bank_Biggest_Secret.txt
> +Категории кэшбэка выпадают на рандоме
лучше без таких приколов в тестовых данных, может быть стыдно потом))

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task3/AbstractFilter.java
> +    boolean accept(Path entry);
это метод родительского интерфейса, необязательно его тут указывать

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test3.java
> +            assertFalse(entries.iterator().hasNext());
такой тест не проверяет, что фильтры реально работают, ты мог в них всех просто false возвращать

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/Task4.java
> +
тут имелось в виду, что ты будешь сразу вкладывать объекты друг в друга, без создания доп. переменных

2023-11-24 13:29 UTC, easylaneof commented on src/test/java/edu/hw6/Test3/lobotomia.txt
> +BOOOOOOOOOOOOoo
тоже самое про тестовые данные (название файла)

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/HackerNews.java
> +public class HackerNews {
[note] все другие задания -- TaskN, а тут нет, я его чуть не потерял)

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/HackerNews.java
> +        } catch (Exception e) {
плохая работа с ошибками

- нужно пробрасывать исключение выше, а не кидать какой-то пустой ответ (как отличить, нам вернулся пустой список или произошла ошибка)
- разные ошибки нужно обрабатывать по разному (не создался uri, упал запрос и тд)

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/HackerNews.java
> +            Pattern pattern = Pattern.compile("\"title\"\\s*:\\s*\"([^\"]+)\"");
лучше вынести в статическое поле класса, потому что иначе ты при каждом вызове метода будешь строить регулярку (а это долго)

2023-11-24 13:29 UTC, easylaneof commented on src/main/java/edu/hw6/HackerNews.java
> +            return "Error";
тоже самое, что выше про исключения

2023-11-26 16:46 UTC, Ltaudato1 commented on src/test/java/edu/hw6/Test1.java
> +public class Test1 {
а зачем тогда нужен пакет "test/java/edu"? нам на вводном занятии сказали все тесты здесь сохранять

2023-12-30 21:45 UTC, merged